### ISSUE TITLE
Request: example of command-line authentication

### ISSUE THREAD

**Issue by gvwilson** [Imgur/imgurpython#30]
I would like to write a small command-line program to upload several hundred files extracted from an old WordPress blog.  I've read this library's docs and the Imgur API docs, but still don't understand how to authenticate (I don't have a URL to redirect to for obtaining a PIN).  Can the examples please include one showing how to authenticate from the command line starting with just a client ID and client secret?

**Comment by RandomInsano** [comment]
I actually just wrote one yesterday.

@jacobgreenleaf @Jasdev: do you guys mind if I split the examples out into a folder with runnable python scripts, then contribute a simple image upload example?

**Comment by Jasdev** [comment]
@RandomInsano That'd be great!

**Comment by RandomInsano** [comment]
Merge request submitted properly now. It's a bit heavy, so if it's a no-go, I'll throw it into the examples document.
