### ISSUE TITLE
Automatic authorization

### ISSUE THREAD

**Issue by patillacode** [Imgur/imgurpython#51]
Hi, 

I was wondering how do an automatic authorization from within the code.

In the README I can see:
```python
# ... redirect user to `authorization_url`, obtain pin (or code or token) ...
```
But I want to grab the pin automatically, since the authorization url redirects me to the actual url with the pin I am not sure how to follow that stream since the [requests library] (http://docs.python-requests.org/en/latest/api/#main-interface) only follows on POST/GET/DELETE methods.

My app has no user interface, I need to get the pin from the code, with no human interaction.
Any suggestions?

Thanks!

**Comment by jacobgreenleaf** [comment]
Can you describe your use case a bit more? We require the end-user to authorize your application at least once so you will need to direct them to the authorize page for their consent. After that it should be possible to programmatically obtain access tokens.

**Comment by patillacode** [comment]
I want to access my imgur account to push images etc

In order to do this I need authorization, so I need to access the authorization url and from there (getting redirected) I get the pin.

How to do that automatically? I don't want to grab the pin manually every hour to set it up in the code to be able to do this.

**Comment by btipling** [comment]
You can do that automatically by sending a [`refresh_token` request](https://api.imgur.com/oauth2#refresh_tokens). This library provides you with a [`refresh` method to do achieve this](https://github.com/Imgur/imgurpython/blob/534c2c8d346e7067b78036f7ece9a1d36a6be18e/imgurpython/client.py#L40).

**Comment by patillacode** [comment]
Well, it seems like I didn't understand the process.

I will look into it again and let you know. 

Thanks guys

**Comment by patillacode** [comment]
Cheers guys, solved.
Understood the refresh way of doing it :smile: 

Thanks for your help.

**Comment by jacobgreenleaf** [comment]
Cool, I will close this as fixed / no issue.

**Comment by ouzkagan** [comment]
> Well, it seems like I didn't understand the process.
> 
> I will look into it again and let you know.
> 
> Thanks guys

lol how??

**Comment by ouzkagan** [comment]
**Oh okay. i understand too ->**
in the official example [https://github.com/Imgur/imgurpython/blob/master/examples/auth.py](auth.py) you get access by _pin_ code. 
just add your access_token and refresh_token to auth.ini file. then construct a instance of ImgurClient with sendind them as a parameter. 


```
access_token = config.get('credentials', 'access_token')
refresh_token = config.get('credentials', 'refresh_token')

client = ImgurClient(client_id, client_secret, access_token, refresh_token)
client.set_user_auth(access_token, refresh_token)
```

may be u don't need to send in both of them.. 

_Also delete pin related parts_
