### ISSUE TITLE
Update PyPi

### ISSUE THREAD

**Issue by viniciusjarina** [Imgur/imgurpython#61]
Hi
It seems pypi package is not update since April
https://pypi.python.org/pypi/imgurpython/1.1.6
Any idea when a new version will be released ?

Thank you.

**Comment by OrganicIrradiation** [comment]
@jacobgreenleaf mentioned 22 days ago that he would push the updated version to PyPI: https://github.com/Imgur/imgurpython/pull/56

**Comment by jacobgreenleaf** [comment]
Hey, I had set up Travis but forgot to push a tagged version to trigger the deployment. See [Build #9](https://travis-ci.org/Imgur/imgurpython/builds/109124089) which did the push. Closing as fixed.
